import type { GrammarCategory, GrammarPack, GrammarPrompt } from "../types/gameTypes";

type PromptSeed = [string, GrammarCategory, string];

const yesSeeds: PromptSeed[] = [
  ["twenty-one", "compound-number", "Numbers from twenty-one to ninety-nine are hyphenated when written as words."],
  ["thirty-two", "compound-number", "Numbers from twenty-one to ninety-nine use a hyphen."],
  ["forty-five", "compound-number", "Compound numbers between twenty-one and ninety-nine require a hyphen."],
  ["fifty-six", "compound-number", "Written compound numbers in this range are joined with a hyphen."],
  ["sixty-seven", "compound-number", "The two-word number is hyphenated."],
  ["seventy-eight", "compound-number", "Numbers from twenty-one to ninety-nine need a hyphen."],
  ["eighty-four", "compound-number", "This written compound number requires a hyphen."],
  ["ninety-nine", "compound-number", "Numbers from twenty-one to ninety-nine are hyphenated."],
  ["self-control", "prefix-suffix", "Compounds beginning with self usually take a hyphen."],
  ["self-esteem", "prefix-suffix", "Self compounds are normally hyphenated."],
  ["self-aware", "prefix-suffix", "Self plus another word is usually joined with a hyphen."],
  ["self-taught", "prefix-suffix", "Self compounds use a hyphen for clarity."],
  ["ex-husband", "prefix-suffix", "The prefix ex meaning former is normally hyphenated."],
  ["ex-president", "prefix-suffix", "Ex meaning former is joined to the noun with a hyphen."],
  ["ex-student", "prefix-suffix", "Ex meaning former takes a hyphen before the noun."],
  ["mother-in-law", "family-compound", "This fixed family compound is written with hyphens."],
  ["father-in-law", "family-compound", "This family relationship term is a fixed hyphenated compound."],
  ["sister-in-law", "family-compound", "This fixed relationship term requires hyphens."],
  ["brother-in-law", "family-compound", "This family compound is conventionally hyphenated."],
  ["well-known", "compound-adjective", "Before a noun, this compound adjective is hyphenated."],
  ["high-speed", "compound-adjective", "The words work together as one adjective before a noun."],
  ["ten-year-old", "compound-adjective", "Age terms used as compound adjectives are hyphenated."],
  ["six-year-old", "compound-adjective", "A compound age adjective takes hyphens."],
  ["old-fashioned", "compound-adjective", "This fixed compound adjective is hyphenated."],
  ["never-ending", "compound-adjective", "This compound adjective is written with a hyphen."],
  ["state-of-the-art", "compound-adjective", "A multi-word compound adjective is joined with hyphens."],
  ["left-handed", "compound-adjective", "This fixed compound adjective is hyphenated."],
  ["right-handed", "compound-adjective", "This compound adjective is conventionally hyphenated."],
  ["world-class", "compound-adjective", "The words combine as one adjective and take a hyphen."],
  ["full-time", "compound-adjective", "This compound adjective is normally hyphenated."],
  ["part-time", "compound-adjective", "This compound adjective is normally hyphenated."],
  ["long-term", "compound-adjective", "Before a noun, this compound adjective uses a hyphen."],
  ["short-term", "compound-adjective", "Before a noun, this compound adjective uses a hyphen."],
  ["middle-aged", "compound-adjective", "This fixed compound adjective is hyphenated."],
  ["last-minute", "compound-adjective", "This compound adjective before a noun takes a hyphen."],
  ["first-class", "compound-adjective", "This compound adjective is conventionally hyphenated."],
  ["user-friendly", "compound-adjective", "The words form one adjective and are hyphenated."],
  ["well-behaved", "compound-adjective", "Before a noun, this compound adjective takes a hyphen."],
  ["well-organised", "compound-adjective", "Before a noun, this compound adjective takes a hyphen."],
  ["well-written", "compound-adjective", "Before a noun, this compound adjective takes a hyphen."],
  ["up-to-date", "compound-adjective", "This multi-word compound adjective is hyphenated."],
  ["one-way", "compound-adjective", "This compound adjective is written with a hyphen."],
  ["two-storey", "compound-adjective", "This number-plus-noun compound adjective uses a hyphen."],
  ["three-page", "compound-adjective", "This number-plus-noun adjective takes a hyphen before a noun."],
  ["all-purpose", "compound-adjective", "This fixed compound adjective is hyphenated."],
  ["ready-made", "compound-adjective", "This compound adjective is conventionally hyphenated."],
  ["well-lit", "compound-adjective", "Before a noun, this compound adjective takes a hyphen."],
  ["deep-sea", "compound-adjective", "This compound adjective uses a hyphen before a noun."],
  ["eye-catching", "compound-adjective", "This compound adjective is written with a hyphen."],
  ["record-breaking", "compound-adjective", "This compound adjective is hyphenated before a noun."],
  ["time-saving", "compound-adjective", "This compound adjective is hyphenated."],
  ["water-resistant", "compound-adjective", "This compound adjective is conventionally hyphenated."],
  ["problem-solving", "compound-adjective", "This compound adjective is hyphenated before a noun."],
  ["English-speaking", "compound-adjective", "This compound adjective uses a hyphen."],
  ["hard-working", "compound-adjective", "This compound adjective is commonly hyphenated."],
  ["one-third", "fixed-compound", "Written fractions used as compounds are hyphenated."],
  ["two-thirds", "fixed-compound", "Written fractions used as compounds are hyphenated."],
  ["check-in", "fixed-compound", "As a noun, check-in is a fixed hyphenated compound."],
  ["runner-up", "fixed-compound", "This fixed compound noun is hyphenated."]
];

const noSeeds: PromptSeed[] = [
  ["bus stop", "open-compound", "Bus stop is a standard open compound noun and does not need a hyphen."],
  ["school bag", "open-compound", "School bag is an open compound noun."],
  ["swimming pool", "open-compound", "Swimming pool is normally written as two words."],
  ["lunch box", "open-compound", "Lunch box is a standard open compound noun."],
  ["football team", "open-compound", "Football team is an open noun phrase."],
  ["kitchen table", "open-compound", "Kitchen table is an open compound noun."],
  ["pencil case", "open-compound", "Pencil case is normally written as two words."],
  ["mountain road", "open-compound", "Mountain road is an open noun phrase."],
  ["rainy day", "adjective-noun", "A simple adjective before a noun does not take a hyphen."],
  ["clever student", "adjective-noun", "A normal adjective-noun pair does not require a hyphen."],
  ["noisy class", "adjective-noun", "A single adjective before a noun is not hyphenated."],
  ["happy dog", "adjective-noun", "A normal adjective-noun phrase has no hyphen."],
  ["quick fox", "adjective-noun", "A single adjective before a noun does not need a hyphen."],
  ["strong wind", "adjective-noun", "A normal adjective-noun phrase is written without a hyphen."],
  ["red apple", "adjective-noun", "Colour adjectives before nouns do not usually take hyphens."],
  ["blue car", "adjective-noun", "Colour adjectives before nouns do not usually take hyphens."],
  ["green field", "adjective-noun", "A simple adjective-noun pair needs no hyphen."],
  ["quiet room", "adjective-noun", "A normal adjective before a noun is not hyphenated."],
  ["bright light", "adjective-noun", "A simple adjective-noun phrase does not require a hyphen."],
  ["heavy rain", "adjective-noun", "A normal adjective-noun phrase has no hyphen."],
  ["maths lesson", "open-compound", "Maths lesson is an open noun phrase."],
  ["science lab", "open-compound", "Science lab is normally written as two words."],
  ["history book", "open-compound", "History book is an open compound noun."],
  ["English class", "open-compound", "English class is a normal open noun phrase."],
  ["sports day", "open-compound", "Sports day is a standard open compound."],
  ["classroom door", "open-compound", "Classroom door is written without a hyphen."],
  ["library card", "open-compound", "Library card is an open compound noun."],
  ["train station", "open-compound", "Train station is written as two words."],
  ["coffee cup", "open-compound", "Coffee cup is an open compound noun."],
  ["water bottle", "open-compound", "Water bottle is normally written as two words."],
  ["garden path", "open-compound", "Garden path is an open noun phrase."],
  ["phone charger", "open-compound", "Phone charger is an open compound noun."],
  ["desk lamp", "open-compound", "Desk lamp is normally written as two words."],
  ["movie night", "open-compound", "Movie night is an open compound noun."],
  ["music room", "open-compound", "Music room is a standard open compound."],
  ["paper plane", "open-compound", "Paper plane is written as two words."],
  ["family dinner", "open-compound", "Family dinner is an open noun phrase."],
  ["river bank", "open-compound", "River bank is a standard open compound noun."],
  ["city park", "open-compound", "City park is written without a hyphen."],
  ["winter coat", "open-compound", "Winter coat is an open compound noun."],
  ["summer holiday", "open-compound", "Summer holiday is written as two words."],
  ["morning bell", "open-compound", "Morning bell is an open noun phrase."],
  ["silver coin", "adjective-noun", "A simple adjective-noun phrase does not take a hyphen."],
  ["wooden chair", "adjective-noun", "A single adjective before a noun is not hyphenated."],
  ["plastic ruler", "adjective-noun", "A normal adjective-noun phrase has no hyphen."],
  ["silent hallway", "adjective-noun", "A single adjective before a noun needs no hyphen."],
  ["friendly teacher", "adjective-noun", "A normal adjective-noun phrase is not hyphenated."],
  ["brave captain", "adjective-noun", "A simple adjective before a noun is written without a hyphen."],
  ["fresh bread", "adjective-noun", "A normal adjective-noun phrase needs no hyphen."],
  ["small island", "adjective-noun", "A simple adjective-noun pair is not hyphenated."],
  ["large window", "adjective-noun", "A normal adjective before a noun has no hyphen."],
  ["ancient castle", "adjective-noun", "A single adjective before a noun does not take a hyphen."],
  ["careful answer", "adjective-noun", "A simple adjective-noun phrase is written without a hyphen."],
  ["final chapter", "adjective-noun", "A single adjective before a noun is not hyphenated."],
  ["daily routine", "adjective-noun", "A normal adjective-noun phrase does not need a hyphen."],
  ["gold medal", "open-compound", "Gold medal is a standard open compound noun."],
  ["team captain", "open-compound", "Team captain is an open compound noun."],
  ["lesson plan", "open-compound", "Lesson plan is normally written as two words."],
  ["reading task", "open-compound", "Reading task is an open noun phrase."],
  ["writing folder", "open-compound", "Writing folder is written without a hyphen."]
];

const yesPrompts: Omit<GrammarPrompt, "id">[] = yesSeeds.map(([phrase, category, explanation]) => ({
  phrase,
  answer: "yes",
  category,
  explanation
}));

const noPrompts: Omit<GrammarPrompt, "id">[] = noSeeds.map(([phrase, category, explanation]) => ({
  phrase,
  answer: "no",
  category,
  explanation
}));

const prompts = [...yesPrompts, ...noPrompts].map((prompt, index) => ({
  ...prompt,
  id: `hyphen-${index + 1}`
}));

export const hyphenPack: GrammarPack = {
  id: "hyphen-year-8",
  name: "Hyphen Battleships",
  yearLevel: "Year 8 English",
  description: "Clear binary practice with compound adjectives, written numbers, fixed compounds, and open compounds.",
  prompts
};
